-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO as i
JOIN REST_REVIEW as j ON i.REST_ID = j.REST_ID
GROUP BY j.REST_ID
HAVING i.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC

# 같은 REST_ID를 가진 애들끼리의 스코어 평균을 내야함.