SELECT TITLE, i.BOARD_ID, j.REPLY_ID, j.WRITER_ID, j.CONTENTS, DATE_FORMAT(j.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE 
FROM USED_GOODS_BOARD as i
JOIN USED_GOODS_REPLY as j ON i.BOARD_ID = j.BOARD_ID
WHERE i.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY j.CREATED_DATE ASC, TITLE ASC